-- Supabase SQL Editor에서 실행하세요.
-- Auth → Email(매직 링크) 활성화 필요

create table if not exists public.user_data (
  user_id uuid primary key references auth.users (id) on delete cascade,
  nickname text not null default '',
  history jsonb not null default '[]'::jsonb,
  pins jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_data enable row level security;

create policy "Users read own data"
  on public.user_data for select
  using (auth.uid() = user_id);

create policy "Users insert own data"
  on public.user_data for insert
  with check (auth.uid() = user_id);

create policy "Users update own data"
  on public.user_data for update
  using (auth.uid() = user_id);

create policy "Users delete own data"
  on public.user_data for delete
  using (auth.uid() = user_id);

-- 피드백 (NEXT_PUBLIC_DB_PROVIDER=supabase)
create table if not exists public.feedbacks (
  id bigint generated by default as identity primary key,
  content_type text not null,
  content_id text not null,
  result_id text,
  rating smallint not null check (rating between 1 and 5),
  liked boolean not null default false,
  comment text not null default '',
  created_at timestamptz not null default now()
);

alter table public.feedbacks enable row level security;

create policy "Anyone can insert feedback"
  on public.feedbacks for insert
  with check (true);

create policy "No public read on feedback"
  on public.feedbacks for select
  using (false);
