import type { TestQuestion } from "../types";

/** MBTI 강제선택 93문항 — Form M A/B 스타일 (축별 균등, gen-mbti-forced.mjs) */
export const MBTI_FORCED_QUESTIONS: TestQuestion[] = [
  { id: "fq1", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "모임이 끝나면 사람들과 더 이야기하고 싶다.", optionB: "혼자만의 시간이 있어야 에너지가 회복된다.", poleA: "E", poleB: "I" } },
  { id: "fq2", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "새로운 사람을 만나는 것이 즐겁다.", optionB: "깊은 대화는 소수와 나누는 편이 좋다.", poleA: "E", poleB: "I" } },
  { id: "fq3", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "활발한 토론에서 에너지를 얻는다.", optionB: "조용한 환경에서 집중이 잘 된다.", poleA: "E", poleB: "I" } },
  { id: "fq4", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "전화·메신저로 연락이 오면 대화가 이어지면 좋다.", optionB: "생각을 정리할 때 혼자 조용히 하는 편이다.", poleA: "E", poleB: "I" } },
  { id: "fq5", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "파티·모임·행사에 가면 기분이 좋아진다.", optionB: "많은 사람 앞에서 말하기보다 1:1 대화를 선호한다.", poleA: "E", poleB: "I" } },
  { id: "fq6", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "에너지를 쓰고 나면 사람들과 함께 있을 때 충전된다.", optionB: "혼자만의 시간이 있어야 에너지가 회복된다.", poleA: "E", poleB: "I" } },
  { id: "fq7", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "처음 보는 모임에서도 자연스럽게 대화를 시작한다.", optionB: "깊은 대화는 소수와 나누는 편이 좋다.", poleA: "E", poleB: "I" } },
  { id: "fq8", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "주말에도 사람들과 만나는 약속이 있으면 기분이 좋다.", optionB: "조용한 환경에서 집중이 잘 된다.", poleA: "E", poleB: "I" } },
  { id: "fq9", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "생각을 말로 꺼내면서 정리하는 편이다.", optionB: "생각을 정리할 때 혼자 조용히 하는 편이다.", poleA: "E", poleB: "I" } },
  { id: "fq10", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "혼자보다 팀·그룹 활동이 더 편하다.", optionB: "많은 사람 앞에서 말하기보다 1:1 대화를 선호한다.", poleA: "E", poleB: "I" } },
  { id: "fq11", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "낯선 환경에서도 금방 적응한다.", optionB: "혼자만의 시간이 있어야 에너지가 회복된다.", poleA: "E", poleB: "I" } },
  { id: "fq12", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "연락이 끊기면 먼저 안부를 묻는다.", optionB: "깊은 대화는 소수와 나누는 편이 좋다.", poleA: "E", poleB: "I" } },
  { id: "fq13", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "에너지가 떨어지면 사람들과 어울리며 회복한다.", optionB: "조용한 환경에서 집중이 잘 된다.", poleA: "E", poleB: "I" } },
  { id: "fq14", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "발표·발언 자리를 피하지 않는다.", optionB: "생각을 정리할 때 혼자 조용히 하는 편이다.", poleA: "E", poleB: "I" } },
  { id: "fq15", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "카페·공간에서도 옆 사람과 대화가 이어지면 좋다.", optionB: "많은 사람 앞에서 말하기보다 1:1 대화를 선호한다.", poleA: "E", poleB: "I" } },
  { id: "fq16", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "조용히 혼자 있는 시간이 길면 지루하다.", optionB: "혼자만의 시간이 있어야 에너지가 회복된다.", poleA: "E", poleB: "I" } },
  { id: "fq17", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "아이디어는 혼자보다 함께 토론할 때 잘 떠오른다.", optionB: "깊은 대화는 소수와 나누는 편이 좋다.", poleA: "E", poleB: "I" } },
  { id: "fq18", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "행사·파티 초대를 받으면 대체로 참석한다.", optionB: "조용한 환경에서 집중이 잘 된다.", poleA: "E", poleB: "I" } },
  { id: "fq19", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "모임이 끝나면 사람들과 더 이야기하고 싶다.", optionB: "생각을 정리할 때 혼자 조용히 하는 편이다.", poleA: "E", poleB: "I" } },
  { id: "fq20", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "새로운 사람을 만나는 것이 즐겁다.", optionB: "많은 사람 앞에서 말하기보다 1:1 대화를 선호한다.", poleA: "E", poleB: "I" } },
  { id: "fq21", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "활발한 토론에서 에너지를 얻는다.", optionB: "혼자만의 시간이 있어야 에너지가 회복된다.", poleA: "E", poleB: "I" } },
  { id: "fq22", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "전화·메신저로 연락이 오면 대화가 이어지면 좋다.", optionB: "깊은 대화는 소수와 나누는 편이 좋다.", poleA: "E", poleB: "I" } },
  { id: "fq23", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "파티·모임·행사에 가면 기분이 좋아진다.", optionB: "조용한 환경에서 집중이 잘 된다.", poleA: "E", poleB: "I" } },
  { id: "fq24", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "에너지를 쓰고 나면 사람들과 함께 있을 때 충전된다.", optionB: "생각을 정리할 때 혼자 조용히 하는 편이다.", poleA: "E", poleB: "I" } },
  { id: "fq25", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "사실과 경험에 근거한 정보를 신뢰한다.", optionB: "가능성과 아이디어를 상상하는 것을 좋아한다.", poleA: "S", poleB: "N" } },
  { id: "fq26", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "구체적인 단계와 실무 디테일을 중시한다.", optionB: "패턴과 의미를 연결해 큰 그림을 본다.", poleA: "S", poleB: "N" } },
  { id: "fq27", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "검증된 방법을 따르는 것이 안전하다.", optionB: "새로운 방식을 시도해 보는 것을 즐긴다.", poleA: "S", poleB: "N" } },
  { id: "fq28", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "지금 당장 손에 잡히는 사실이 중요하다.", optionB: "'왜?' '만약?' 같은 질문을 자주 한다.", poleA: "S", poleB: "N" } },
  { id: "fq29", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "매뉴얼·레시피·순서대로 하는 것이 편하다.", optionB: "상징·은유·미래 시나리오를 떠올리는 편이다.", poleA: "S", poleB: "N" } },
  { id: "fq30", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "경험과 사례를 바탕으로 판단한다.", optionB: "가능성과 아이디어를 상상하는 것을 좋아한다.", poleA: "S", poleB: "N" } },
  { id: "fq31", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "지금 눈앞의 사실·숫자·증거를 먼저 본다.", optionB: "패턴과 의미를 연결해 큰 그림을 본다.", poleA: "S", poleB: "N" } },
  { id: "fq32", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "설명서·매뉴얼을 꼼꼼히 읽는 편이다.", optionB: "새로운 방식을 시도해 보는 것을 즐긴다.", poleA: "S", poleB: "N" } },
  { id: "fq33", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "과거 경험이 비슷한 상황의 기준이 된다.", optionB: "'왜?' '만약?' 같은 질문을 자주 한다.", poleA: "S", poleB: "N" } },
  { id: "fq34", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "현실적으로 실행 가능한지부터 따진다.", optionB: "상징·은유·미래 시나리오를 떠올리는 편이다.", poleA: "S", poleB: "N" } },
  { id: "fq35", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "세부 사항 하나하나가 중요하다.", optionB: "가능성과 아이디어를 상상하는 것을 좋아한다.", poleA: "S", poleB: "N" } },
  { id: "fq36", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "이론보다 실제 사례·예시가 이해에 도움 된다.", optionB: "패턴과 의미를 연결해 큰 그림을 본다.", poleA: "S", poleB: "N" } },
  { id: "fq37", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "미래 가능성보다 현재 상황을 먼저 처리한다.", optionB: "새로운 방식을 시도해 보는 것을 즐긴다.", poleA: "S", poleB: "N" } },
  { id: "fq38", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "구체적인 예시 없으면 개념이 잘 와닿지 않는다.", optionB: "'왜?' '만약?' 같은 질문을 자주 한다.", poleA: "S", poleB: "N" } },
  { id: "fq39", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "눈에 보이는 결과·성과를 중시한다.", optionB: "상징·은유·미래 시나리오를 떠올리는 편이다.", poleA: "S", poleB: "N" } },
  { id: "fq40", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "단계별로 차근차근 진행하는 것을 선호한다.", optionB: "가능성과 아이디어를 상상하는 것을 좋아한다.", poleA: "S", poleB: "N" } },
  { id: "fq41", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "데이터·통계·측정 가능한 기준을 신뢰한다.", optionB: "패턴과 의미를 연결해 큰 그림을 본다.", poleA: "S", poleB: "N" } },
  { id: "fq42", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "오감으로 확인한 정보를 더 믿는다.", optionB: "새로운 방식을 시도해 보는 것을 즐긴다.", poleA: "S", poleB: "N" } },
  { id: "fq43", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "사실과 경험에 근거한 정보를 신뢰한다.", optionB: "'왜?' '만약?' 같은 질문을 자주 한다.", poleA: "S", poleB: "N" } },
  { id: "fq44", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "구체적인 단계와 실무 디테일을 중시한다.", optionB: "상징·은유·미래 시나리오를 떠올리는 편이다.", poleA: "S", poleB: "N" } },
  { id: "fq45", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "검증된 방법을 따르는 것이 안전하다.", optionB: "가능성과 아이디어를 상상하는 것을 좋아한다.", poleA: "S", poleB: "N" } },
  { id: "fq46", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "지금 당장 손에 잡히는 사실이 중요하다.", optionB: "패턴과 의미를 연결해 큰 그림을 본다.", poleA: "S", poleB: "N" } },
  { id: "fq47", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "매뉴얼·레시피·순서대로 하는 것이 편하다.", optionB: "새로운 방식을 시도해 보는 것을 즐긴다.", poleA: "S", poleB: "N" } },
  { id: "fq48", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "결정할 때 논리와 객관적 기준을 우선한다.", optionB: "결정할 때 사람의 감정과 조화를 고려한다.", poleA: "T", poleB: "F" } },
  { id: "fq49", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "비판은 개선을 위한 정보로 받아들인다.", optionB: "갈등을 피하기 위해 상대 기분을 먼저 살핀다.", poleA: "T", poleB: "F" } },
  { id: "fq50", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "원칙과 공정함이 관계보다 우선일 때가 있다.", optionB: "상대가 상처받을까 먼저 걱정한다.", poleA: "T", poleB: "F" } },
  { id: "fq51", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "감정보다 사실·데이터를 말하는 편이다.", optionB: "팀 분위기를 해치지 않으려 노력한다.", poleA: "T", poleB: "F" } },
  { id: "fq52", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "냉정하게 분석하면 감정도 정리된다고 느낀다.", optionB: "타인의 감정을 먼저 읽으려 노력한다.", poleA: "T", poleB: "F" } },
  { id: "fq53", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "원칙·규칙이 감정보다 우선일 때가 있다.", optionB: "분위기·조화가 결과만큼 중요하다.", poleA: "T", poleB: "F" } },
  { id: "fq54", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "문제 해결 시 객관적 기준이 공정하다고 느낀다.", optionB: "결정할 때 사람의 감정과 조화를 고려한다.", poleA: "T", poleB: "F" } },
  { id: "fq55", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "솔직한 피드백이 관계를 더 건강하게 만든다.", optionB: "갈등을 피하기 위해 상대 기분을 먼저 살핀다.", poleA: "T", poleB: "F" } },
  { id: "fq56", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "결정 근거를 논리적으로 설명하는 편이다.", optionB: "상대가 상처받을까 먼저 걱정한다.", poleA: "T", poleB: "F" } },
  { id: "fq57", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "감정적 호소보다 사실 확인이 먼저다.", optionB: "팀 분위기를 해치지 않으려 노력한다.", poleA: "T", poleB: "F" } },
  { id: "fq58", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "경쟁·성과 비교가 동기부여가 될 때가 있다.", optionB: "타인의 감정을 먼저 읽으려 노력한다.", poleA: "T", poleB: "F" } },
  { id: "fq59", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "상대가 틀렸다면 부드럽게라도 지적한다.", optionB: "분위기·조화가 결과만큼 중요하다.", poleA: "T", poleB: "F" } },
  { id: "fq60", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "공정함·일관성을 관계의 기준으로 삼는다.", optionB: "결정할 때 사람의 감정과 조화를 고려한다.", poleA: "T", poleB: "F" } },
  { id: "fq61", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "감정이 앞서면 스스로 냉정해지려 한다.", optionB: "갈등을 피하기 위해 상대 기분을 먼저 살핀다.", poleA: "T", poleB: "F" } },
  { id: "fq62", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "효율·합리성이 최우선 가치에 가깝다.", optionB: "상대가 상처받을까 먼저 걱정한다.", poleA: "T", poleB: "F" } },
  { id: "fq63", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "논쟁에서 사실·논리가 감정보다 설득력 있다.", optionB: "팀 분위기를 해치지 않으려 노력한다.", poleA: "T", poleB: "F" } },
  { id: "fq64", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "결정을 미루기보다 명확한 기준으로 빨리 내린다.", optionB: "타인의 감정을 먼저 읽으려 노력한다.", poleA: "T", poleB: "F" } },
  { id: "fq65", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "결정할 때 논리와 객관적 기준을 우선한다.", optionB: "분위기·조화가 결과만큼 중요하다.", poleA: "T", poleB: "F" } },
  { id: "fq66", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "비판은 개선을 위한 정보로 받아들인다.", optionB: "결정할 때 사람의 감정과 조화를 고려한다.", poleA: "T", poleB: "F" } },
  { id: "fq67", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "원칙과 공정함이 관계보다 우선일 때가 있다.", optionB: "갈등을 피하기 위해 상대 기분을 먼저 살핀다.", poleA: "T", poleB: "F" } },
  { id: "fq68", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "감정보다 사실·데이터를 말하는 편이다.", optionB: "상대가 상처받을까 먼저 걱정한다.", poleA: "T", poleB: "F" } },
  { id: "fq69", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "냉정하게 분석하면 감정도 정리된다고 느낀다.", optionB: "팀 분위기를 해치지 않으려 노력한다.", poleA: "T", poleB: "F" } },
  { id: "fq70", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "원칙·규칙이 감정보다 우선일 때가 있다.", optionB: "타인의 감정을 먼저 읽으려 노력한다.", poleA: "T", poleB: "F" } },
  { id: "fq71", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "일정과 계획을 미리 세우는 편이다.", optionB: "즉흥적으로 일정을 바꿔도 크게 부담되지 않는다.", poleA: "J", poleB: "P" } },
  { id: "fq72", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "마감 전에 미리 끝내 두는 것이 편하다.", optionB: "열린 선택지를 유지하는 것이 안심된다.", poleA: "J", poleB: "P" } },
  { id: "fq73", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "할 일 목록·캘린더 없으면 불안하다.", optionB: "계획 없이 흘러가는 하루도 즐겁다.", poleA: "J", poleB: "P" } },
  { id: "fq74", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "결정을 빨리 내리고 마무리하는 편이다.", optionB: "마감 직전에 집중력이 최고조에 달한다.", poleA: "J", poleB: "P" } },
  { id: "fq75", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "정리·수납·분류를 해두면 마음이 편하다.", optionB: "마감 직전에야 집중이 극대화되는 편이다.", poleA: "J", poleB: "P" } },
  { id: "fq76", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "여행·일정은 미리 계획해 두는 편이다.", optionB: "규칙·틀보다 상황에 맞게 유연하게 움직인다.", poleA: "J", poleB: "P" } },
  { id: "fq77", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "마무리·정리가 안 되면 찜찜하다.", optionB: "계획이 바뀌어도 새 흐름을 즐기는 편이다.", poleA: "J", poleB: "P" } },
  { id: "fq78", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "데드라인을 지키는 것이 자존감과 연결된다.", optionB: "즉흥적으로 일정을 바꿔도 크게 부담되지 않는다.", poleA: "J", poleB: "P" } },
  { id: "fq79", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "결정을 내리고 다음 단계로 넘어가야 편하다.", optionB: "열린 선택지를 유지하는 것이 안심된다.", poleA: "J", poleB: "P" } },
  { id: "fq80", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "집·책상·파일이 정돈되어 있으면 집중이 잘 된다.", optionB: "계획 없이 흘러가는 하루도 즐겁다.", poleA: "J", poleB: "P" } },
  { id: "fq81", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "약속 시간·규칙을 지키는 것이 중요하다.", optionB: "마감 직전에 집중력이 최고조에 달한다.", poleA: "J", poleB: "P" } },
  { id: "fq82", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "프로젝트는 초반에 방향을 확정하는 편이다.", optionB: "마감 직전에야 집중이 극대화되는 편이다.", poleA: "J", poleB: "P" } },
  { id: "fq83", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "미완료 과제가 많으면 스트레스를 받는다.", optionB: "규칙·틀보다 상황에 맞게 유연하게 움직인다.", poleA: "J", poleB: "P" } },
  { id: "fq84", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "선택지를 오래 열어 두면 불안하다.", optionB: "계획이 바뀌어도 새 흐름을 즐기는 편이다.", poleA: "J", poleB: "P" } },
  { id: "fq85", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "계획표·체크리스트를 자주 쓴다.", optionB: "즉흥적으로 일정을 바꿔도 크게 부담되지 않는다.", poleA: "J", poleB: "P" } },
  { id: "fq86", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "갑작스러운 변경보다 예고된 변화가 낫다.", optionB: "열린 선택지를 유지하는 것이 안심된다.", poleA: "J", poleB: "P" } },
  { id: "fq87", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "일을 시작하기 전에 전체 구조를 잡는다.", optionB: "계획 없이 흘러가는 하루도 즐겁다.", poleA: "J", poleB: "P" } },
  { id: "fq88", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "일정과 계획을 미리 세우는 편이다.", optionB: "마감 직전에 집중력이 최고조에 달한다.", poleA: "J", poleB: "P" } },
  { id: "fq89", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "마감 전에 미리 끝내 두는 것이 편하다.", optionB: "마감 직전에야 집중이 극대화되는 편이다.", poleA: "J", poleB: "P" } },
  { id: "fq90", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "할 일 목록·캘린더 없으면 불안하다.", optionB: "규칙·틀보다 상황에 맞게 유연하게 움직인다.", poleA: "J", poleB: "P" } },
  { id: "fq91", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "결정을 빨리 내리고 마무리하는 편이다.", optionB: "계획이 바뀌어도 새 흐름을 즐기는 편이다.", poleA: "J", poleB: "P" } },
  { id: "fq92", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "정리·수납·분류를 해두면 마음이 편하다.", optionB: "즉흥적으로 일정을 바꿔도 크게 부담되지 않는다.", poleA: "J", poleB: "P" } },
  { id: "fq93", text: "두 문장 중 더 나와 가까운 쪽을 선택하세요.", binary: { optionA: "여행·일정은 미리 계획해 두는 편이다.", optionB: "열린 선택지를 유지하는 것이 안심된다.", poleA: "J", poleB: "P" } },
];
