import type { TestQuestion } from "../types";

/** MBTI 40문항 — 축당 10문항 (E/I·S/N·T/F·J/P) */
export const MBTI_QUESTIONS: TestQuestion[] = [
  { id: "q1", text: "모임이 끝나면 사람들과 더 이야기하고 싶다." },
  { id: "q2", text: "혼자만의 시간이 있어야 에너지가 회복된다." },
  { id: "q3", text: "새로운 사람을 만나는 것이 즐겁다." },
  { id: "q4", text: "깊은 대화는 소수와 나누는 편이 좋다." },
  { id: "q5", text: "사실과 경험에 근거한 정보를 신뢰한다." },
  { id: "q6", text: "가능성과 아이디어를 상상하는 것을 좋아한다." },
  { id: "q7", text: "구체적인 단계와 실무 디테일을 중시한다." },
  { id: "q8", text: "패턴과 의미를 연결해 큰 그림을 본다." },
  { id: "q9", text: "결정할 때 논리와 객관적 기준을 우선한다." },
  { id: "q10", text: "결정할 때 사람의 감정과 조화를 고려한다." },
  { id: "q11", text: "비판은 개선을 위한 정보로 받아들인다." },
  { id: "q12", text: "갈등을 피하기 위해 상대 기분을 먼저 살핀다." },
  { id: "q13", text: "일정과 계획을 미리 세우는 편이다." },
  { id: "q14", text: "즉흥적으로 일정을 바꿔도 크게 부담되지 않는다." },
  { id: "q15", text: "마감 전에 미리 끝내 두는 것이 편하다." },
  { id: "q16", text: "열린 선택지를 유지하는 것이 안심된다." },
  { id: "q17", text: "활발한 토론에서 에너지를 얻는다." },
  { id: "q18", text: "조용한 환경에서 집중이 잘 된다." },
  { id: "q19", text: "검증된 방법을 따르는 것이 안전하다." },
  { id: "q20", text: "새로운 방식을 시도해 보는 것을 즐긴다." },
  { id: "q21", text: "전화·메신저로 연락이 오면 대화가 이어지면 좋다." },
  { id: "q22", text: "생각을 정리할 때 혼자 조용히 하는 편이다." },
  { id: "q23", text: "파티·모임·행사에 가면 기분이 좋아진다." },
  { id: "q24", text: "많은 사람 앞에서 말하기보다 1:1 대화를 선호한다." },
  { id: "q25", text: "에너지를 쓰고 나면 사람들과 함께 있을 때 충전된다." },
  { id: "q26", text: "지금 당장 손에 잡히는 사실이 중요하다." },
  { id: "q27", text: "'왜?' '만약?' 같은 질문을 자주 한다." },
  { id: "q28", text: "매뉴얼·레시피·순서대로 하는 것이 편하다." },
  { id: "q29", text: "상징·은유·미래 시나리오를 떠올리는 편이다." },
  { id: "q30", text: "경험과 사례를 바탕으로 판단한다." },
  { id: "q31", text: "원칙과 공정함이 관계보다 우선일 때가 있다." },
  { id: "q32", text: "상대가 상처받을까 먼저 걱정한다." },
  { id: "q33", text: "감정보다 사실·데이터를 말하는 편이다." },
  { id: "q34", text: "팀 분위기를 해치지 않으려 노력한다." },
  { id: "q35", text: "냉정하게 분석하면 감정도 정리된다고 느낀다." },
  { id: "q36", text: "할 일 목록·캘린더 없으면 불안하다." },
  { id: "q37", text: "계획 없이 흘러가는 하루도 즐겁다." },
  { id: "q38", text: "결정을 빨리 내리고 마무리하는 편이다." },
  { id: "q39", text: "마감 직전에 집중력이 최고조에 달한다." },
  { id: "q40", text: "정리·수납·분류를 해두면 마음이 편하다." },
];

export const MBTI_AXES = [
  {
    id: "ei",
    poleA: { key: "E", label: "외향(E)" },
    poleB: { key: "I", label: "내향(I)" },
    questions: {
      q1: { pole: "E" }, q2: { pole: "I" }, q3: { pole: "E" }, q4: { pole: "I" },
      q17: { pole: "E" }, q18: { pole: "I" },
      q21: { pole: "E" }, q22: { pole: "I" }, q23: { pole: "E" }, q24: { pole: "I" },
      q25: { pole: "E" },
    },
  },
  {
    id: "sn",
    poleA: { key: "S", label: "감각(S)" },
    poleB: { key: "N", label: "직관(N)" },
    questions: {
      q5: { pole: "S" }, q6: { pole: "N" }, q7: { pole: "S" }, q8: { pole: "N" },
      q19: { pole: "S" }, q20: { pole: "N" },
      q26: { pole: "S" }, q27: { pole: "N" }, q28: { pole: "S" }, q29: { pole: "N" },
      q30: { pole: "S" },
    },
  },
  {
    id: "tf",
    poleA: { key: "T", label: "사고(T)" },
    poleB: { key: "F", label: "감정(F)" },
    questions: {
      q9: { pole: "T" }, q10: { pole: "F" }, q11: { pole: "T" }, q12: { pole: "F" },
      q31: { pole: "T" }, q32: { pole: "F" }, q33: { pole: "T" }, q34: { pole: "F" },
      q35: { pole: "T" },
    },
  },
  {
    id: "jp",
    poleA: { key: "J", label: "판단(J)" },
    poleB: { key: "P", label: "인식(P)" },
    questions: {
      q13: { pole: "J" }, q14: { pole: "P" }, q15: { pole: "J" }, q16: { pole: "P" },
      q36: { pole: "J" }, q37: { pole: "P" }, q38: { pole: "J" }, q39: { pole: "P" },
      q40: { pole: "J" },
    },
  },
] as const;
